#!/bin/bash
title="Select example"
prompt="Escolha a opção desejada:"
options=("1 - Limpar Diretórios" "2 - Montar ISO e Editar" "3 - Sair")

echo "$title"
PS3="$prompt "
select opt in "${options[@]}" "Quit"; do 

    case "$REPLY" in

    1 ) echo "You picked $opt which is option $REPLY";;
    2 ) echo "You picked $opt which is option $REPLY";;
    3 ) echo "You picked $opt which is option $REPLY";;

    $(( ${#options[@]}+1 )) ) echo "Goodbye!"; break;;
    *) echo "Você deve escolher uma opção!!!";continue;;

    esac

done

while opt=$(zenity --title="$title" --text="$prompt" --list \
                   --column="Options" "${options[@]}"); do

    case "$opt" in
    "${options[0]}" ) xterm -e sudo bash /opt/EditorISO/antescustomizar;;
    "${options[1]}" ) xterm -e sudo bash /opt/EditorISO/Montar\ Imagem\ ISO && xterm -e sudo bash /opt/EditorISO/começar && xterm -e sudo bash /opt/EditorISO/finalizar2 && xterm -e sudo bash /opt/EditorISO/criarISO;;
    "${options[2]}" ) break;;

    *) zenity --error --text="Você deve escolher uma opção!!!";;
    esac
#break

done
