#!/bin/bash
mount -t proc none /proc/
mount -t sysfs none /sys/
export HOME=/root
  
 	echo -e "\e[101m|  Agora você pode iniciar as alterações que desejar, lembrando que 
depois de fazer suas alterações, execute:   |\e[0m"

	echo -e "\e[105m  ./finalizar   \e[0m"
